name: grocery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: ExpoArabic
      fonts:
        - asset: assets\fonts\Expo-Arabic-Light.ttf
          weight: 300
        - asset: assets\fonts\Expo-Arabic-Medium.ttf
          weight: 500
        - asset: assets\fonts\Expo-Arabic-Bold.ttf
          weight: 700
    - family: ArabicRegular
      fonts:
        - asset: assets\fonts\arabic_regular.ttf
          weight: 200
